web:
  restart: "always"
  build: .
  command: flask run -h 0.0.0.0
  environment:
    - FLASK_APP=/code/app.py

nginx:
  restart: "always"
  build: ./nginx
  ports:
    - "80:80"
  links:
    - web
  volumes:
    - /opt/afs/cern.ch/project/cds/invenio/inveniosoftware.org/download:/usr/share/nginx/html/download:ro
