web:
  restart: "always"
  build: .
  command: flask run -h 0.0.0.0
  environment:
    - FLASK_DEBUG=1
    - FLASK_APP=/code/app.py
  ports:
    - "5000:5000"
  volumes:
    - .:/code

nginx:
  restart: "always"
  build: ./nginx
  ports:
    - "80:80"
  links:
    - web
  volumes:
    - .:/code
